---
- hosts: webservers
  become: true
  become_user: root

  tasks:
  - name: remove running container
    command: docker rm -f phpapp
    
  - name: Delete all images
    command: docker image prune -a -f  
 
  - name: clone the repo 
    git: repo=https://github.com/rsadhukhan/edureka-project1.git dest=/gitrepo
   
  - name: loginto docker
    command: docker login --username rsadhukhan --password XXY#760Qbe
    
  - name: change directory and build dockerfile
    command: chdir=/gitrepo docker build -t mywebapp .
    
  - name: run the image to launch container
    command: docker run --name phpapp -itd -p 30008:80 mywebapp
