---
- hosts: webservers
  become: true
  become_user: root

  tasks:
  - name: Delete all running container
    docker_container:
      name: hopeful_clarke
      state: absent
    
  - name: Delete all images
    command: docker image prune -a -f
