---
- hosts: webservers
  become: true
  become_user: root

  tasks:
  - name: clone the repo 
    git: repo=https://github.com/rsadhukhan/edureka-project1.git dest=/gitrepo
   
  - name: loginto docker
    command: docker login --username rsadhukhan --password XXY#760Qbe
    
  - name: change directory and build dockerfile
    command: chdir=/gitrepo docker build -t mywebapp .
    
  - name: run the image to launch container
    command: docker run -itd -p 30008:80 mywebapp
